name: .NET Package Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build and pack
        run: dotnet pack --no-restore -c Release -o ../out
        working-directory: ./src

      - name: Publish package
        run: dotnet nuget push "../out/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: ./src